<?php

namespace Database\Seeders;

use Carbon\Carbon;
use App\Models\Store;
use App\Models\Package;
use App\Models\Package_store;
use App\Models\activities_stores;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class StoreSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
         Store::create([
            'store_name' => 'امازون',
            'store_email' => 'a@gmail.com',
            'domain' => 'https//www.a.com',
            'icon' => 'Amazon_logo.png',
            'phonenumber' => '0096650775433',
            'description' => 'this is amazon store',
            'snapchat' => 'https//www.snapchat.com',
            'facebook' => 'https//www.facebook.com',
            'twiter' => 'https//www.twiter.com',
            'youtube' => 'https//www.youtube.com',
            'instegram' => 'https//www.instegram.com',
            'logo' => 'Amazon_logo.png',
            'periodtype' => 'year',
            'start_at' => '2022-03-01',
            'end_at' => '2023-03-01',
            'package_id' => 1,
            'country_id' => 1,
            'city_id' =>1,
             'user_id'=>null,
             'special'=>'special',

        ]);
 Store::create([
            'store_name' => 'امازون',
            'store_email' => 'a1@gmail.com',
            'domain' => 'https//www.a.com',
            'icon' => 'Amazon_logo.png',
            'phonenumber' => '0096650775433',
            'description' => 'this is amazon store',
            'snapchat' => 'https//www.snapchat.com',
            'facebook' => 'https//www.facebook.com',
            'twiter' => 'https//www.twiter.com',
            'youtube' => 'https//www.youtube.com',
            'instegram' => 'https//www.instegram.com',
            'logo' => 'Amazon_logo.png',
            'periodtype' => 'year',
            'start_at' => '2022-03-01',
            'end_at' => '2023-03-01',
            'package_id' => 1,
            'country_id' => 1,
            'city_id' =>1,
             'user_id'=>null,
             'special'=>'special',

        ]);
 Store::create([
            'store_name' => 'امازون',
            'store_email' => 'a2@gmail.com',
            'domain' => 'https//www.a.com',
            'icon' => 'Amazon_logo.png',
            'phonenumber' => '0096650775433',
            'description' => 'this is amazon store',
            'snapchat' => 'https//www.snapchat.com',
            'facebook' => 'https//www.facebook.com',
            'twiter' => 'https//www.twiter.com',
            'youtube' => 'https//www.youtube.com',
            'instegram' => 'https//www.instegram.com',
            'logo' => 'Amazon_logo.png',
            'periodtype' => 'year',
            'start_at' => '2022-03-01',
            'end_at' => '2023-03-01',
            'package_id' => 1,
            'country_id' => 1,
            'city_id' =>1,
             'user_id'=>null,
             'special'=>'special',

        ]);
         Store::create([
            'store_name' => 'امازون',
            'store_email' => 'a3@gmail.com',
            'domain' => 'https//www.a.com',
            'icon' => 'Amazon_logo.png',
            'phonenumber' => '0096650775433',
            'description' => 'this is amazon store',
            'snapchat' => 'https//www.snapchat.com',
            'facebook' => 'https//www.facebook.com',
            'twiter' => 'https//www.twiter.com',
            'youtube' => 'https//www.youtube.com',
            'instegram' => 'https//www.instegram.com',
            'logo' => 'Amazon_logo.png',
            'periodtype' => 'year',
            'start_at' => '2022-03-01',
            'end_at' => '2023-03-01',
            'package_id' => 1,
            'country_id' => 1,
            'city_id' =>1,
             'user_id'=>null,
             'special'=>'special',

        ]);
         Store::create([
            'store_name' => 'امازون',
            'store_email' => 'a4@gmail.com',
            'domain' => 'https//www.a.com',
            'icon' => 'Amazon_logo.png',
            'phonenumber' => '0096650775433',
            'description' => 'this is amazon store',
            'snapchat' => 'https//www.snapchat.com',
            'facebook' => 'https//www.facebook.com',
            'twiter' => 'https//www.twiter.com',
            'youtube' => 'https//www.youtube.com',
            'instegram' => 'https//www.instegram.com',
            'logo' => 'Amazon_logo.png',
            'periodtype' => 'year',
            'start_at' => '2022-03-01',
            'end_at' => '2023-03-01',
            'package_id' => 1,
            'country_id' => 1,
            'city_id' =>1,
             'user_id'=>null,
             'special'=>'special',

        ]);
         Store::create([
            'store_name' => 'امازون',
            'store_email' => 'a5@gmail.com',
            'domain' => 'https//www.a.com',
            'icon' => 'Amazon_logo.png',
            'phonenumber' => '0096650775433',
            'description' => 'this is amazon store',
            'snapchat' => 'https//www.snapchat.com',
            'facebook' => 'https//www.facebook.com',
            'twiter' => 'https//www.twiter.com',
            'youtube' => 'https//www.youtube.com',
            'instegram' => 'https//www.instegram.com',
            'logo' => 'Amazon_logo.png',
            'periodtype' => 'year',
            'start_at' => '2022-03-01',
            'end_at' => '2023-03-01',
            'package_id' => 1,
            'country_id' => 1,
            'city_id' =>1,
             'user_id'=>null,
             'special'=>'special',

        ]);
         Store::create([
            'store_name' => 'امازون',
            'store_email' => 'a6@gmail.com',
            'domain' => 'https//www.a.com',
            'icon' => 'Amazon_logo.png',
            'phonenumber' => '0096650775433',
            'description' => 'this is amazon store',
            'snapchat' => 'https//www.snapchat.com',
            'facebook' => 'https//www.facebook.com',
            'twiter' => 'https//www.twiter.com',
            'youtube' => 'https//www.youtube.com',
            'instegram' => 'https//www.instegram.com',
            'logo' => 'Amazon_logo.png',
            'periodtype' => 'year',
            'start_at' => '2022-03-01',
            'end_at' => '2023-03-01',
            'package_id' => 1,
            'country_id' => 1,
            'city_id' =>1,
             'user_id'=>null,
             'special'=>'special',

        ]);
         Store::create([
            'store_name' => 'امازون',
            'store_email' => 'a7@gmail.com',
            'domain' => 'https//www.a.com',
            'icon' => 'Amazon_logo.png',
            'phonenumber' => '0096650775433',
            'description' => 'this is amazon store',
            'snapchat' => 'https//www.snapchat.com',
            'facebook' => 'https//www.facebook.com',
            'twiter' => 'https//www.twiter.com',
            'youtube' => 'https//www.youtube.com',
            'instegram' => 'https//www.instegram.com',
            'logo' => 'Amazon_logo.png',
            'periodtype' => 'year',
            'start_at' => '2022-03-01',
            'end_at' => '2023-03-01',
            'package_id' => 1,
            'country_id' => 1,
            'city_id' =>1,
             'user_id'=>null,
             'special'=>'special',

        ]);
         Store::create([
            'store_name' => 'نون',
            'store_email' => 'b@gmail.com',
            'domain' => 'https//www.n.com',
            'icon' => 'noon.png',
            'phonenumber' => '0096650775433',
            'description' => 'this is noon store',
            'snapchat' => 'https//www.snapchat.com',
            'facebook' => 'https//www.facebook.com',
            'twiter' => 'https//www.twiter.com',
            'youtube' => 'https//www.youtube.com',
            'instegram' => 'https//www.instegram.com',
            'logo' => 'noon.png',
           'periodtype' => 'year',
            'start_at' => '2022-03-01',
            'end_at' => '2023-03-01',
            'package_id' => 1,
            'country_id' => 1,
            'city_id' =>1,
            'user_id'=>null,
            'special'=>'special',

        ]);
             Store::create([
            'store_name' => 'نون',
            'store_email' => 'c@gmail.com',
            'domain' => 'https//www.n.com',
            'icon' => 'noon.png',
            'phonenumber' => '0096650775433',
            'description' => 'this is noon store',
            'snapchat' => 'https//www.snapchat.com',
            'facebook' => 'https//www.facebook.com',
            'twiter' => 'https//www.twiter.com',
            'youtube' => 'https//www.youtube.com',
            'instegram' => 'https//www.instegram.com',
            'logo' => 'noon.png',
           'periodtype' => 'year',
            'start_at' => '2022-03-01',
            'end_at' => '2023-03-01',
            'package_id' => 1,
            'country_id' => 1,
            'city_id' =>1,
            'user_id'=>null,
            'special'=>'special',

        ]);
          Store::create([
            'store_name' => 'نون',
            'store_email' => 'd@gmail.com',
            'domain' => 'https//www.n.com',
            'icon' => 'noon.png',
            'phonenumber' => '0096650775433',
            'description' => 'this is noon store',
            'snapchat' => 'https//www.snapchat.com',
            'facebook' => 'https//www.facebook.com',
            'twiter' => 'https//www.twiter.com',
            'youtube' => 'https//www.youtube.com',
            'instegram' => 'https//www.instegram.com',
            'logo' => 'noon.png',
           'periodtype' => 'year',
            'start_at' => '2022-03-01',
            'end_at' => '2023-03-01',
            'package_id' => 1,
            'country_id' => 1,
            'city_id' =>1,
            'user_id'=>null,
            'special'=>'special',

        ]);
         Store::create([
            'store_name' => 'نون',
            'store_email' => 'e@gmail.com',
            'domain' => 'https//www.n.com',
            'icon' => 'noon.png',
            'phonenumber' => '0096650775433',
            'description' => 'this is noon store',
            'snapchat' => 'https//www.snapchat.com',
            'facebook' => 'https//www.facebook.com',
            'twiter' => 'https//www.twiter.com',
            'youtube' => 'https//www.youtube.com',
            'instegram' => 'https//www.instegram.com',
            'logo' => 'noon.png',
           'periodtype' => 'year',
            'start_at' => '2022-03-01',
            'end_at' => '2023-03-01',
            'package_id' => 1,
            'country_id' => 1,
            'city_id' =>1,
            'user_id'=>null,
            'special'=>'special',

        ]);
         Store::create([
            'store_name' => 'نون',
            'store_email' => 'f@gmail.com',
            'domain' => 'https//www.n.com',
            'icon' => 'noon.png',
            'phonenumber' => '0096650775433',
            'description' => 'this is noon store',
            'snapchat' => 'https//www.snapchat.com',
            'facebook' => 'https//www.facebook.com',
            'twiter' => 'https//www.twiter.com',
            'youtube' => 'https//www.youtube.com',
            'instegram' => 'https//www.instegram.com',
            'logo' => 'noon.png',
           'periodtype' => 'year',
            'start_at' => '2022-03-01',
            'end_at' => '2023-03-01',
            'package_id' => 1,
            'country_id' => 1,
            'city_id' =>1,
            'user_id'=>null,
            'special'=>'special',

        ]);
         Store::create([
            'store_name' => 'نون',
            'store_email' => 'g@gmail.com',
            'domain' => 'https//www.n.com',
            'icon' => 'noon.png',
            'phonenumber' => '0096650775433',
            'description' => 'this is noon store',
            'snapchat' => 'https//www.snapchat.com',
            'facebook' => 'https//www.facebook.com',
            'twiter' => 'https//www.twiter.com',
            'youtube' => 'https//www.youtube.com',
            'instegram' => 'https//www.instegram.com',
            'logo' => 'noon.png',
           'periodtype' => 'year',
            'start_at' => '2022-03-01',
            'end_at' => '2023-03-01',
            'package_id' => 1,
            'country_id' => 1,
            'city_id' =>1,
            'user_id'=>null,
            'special'=>'special',

        ]);
         Store::create([
            'store_name' => 'امازون',
            'store_email' => 'h@gmail.com',
            'domain' => 'https//www.a.com',
            'icon' => 'Amazon_logo.png',
            'phonenumber' => '0096650775433',
            'description' => 'this is amazon store',
            'snapchat' => 'https//www.snapchat.com',
            'facebook' => 'https//www.facebook.com',
            'twiter' => 'https//www.twiter.com',
            'youtube' => 'https//www.youtube.com',
            'instegram' => 'https//www.instegram.com',
            'logo' => 'Amazon_logo.png',
            'periodtype' => 'year',
            'start_at' => '2022-03-01',
            'end_at' => '2023-03-01',
            'package_id' => 1,
            'country_id' => 1,
            'city_id' =>1,
             'user_id'=>null,
             'special'=>'special',

        ]);


         Store::create([
            'store_name' => 'نون',
            'store_email' => 'i@gmail.com',
            'domain' => 'https//www.n.com',
            'icon' => 'noon.png',
            'phonenumber' => '0096650775433',
            'description' => 'this is noon store',
            'snapchat' => 'https//www.snapchat.com',
            'facebook' => 'https//www.facebook.com',
            'twiter' => 'https//www.twiter.com',
            'youtube' => 'https//www.youtube.com',
            'instegram' => 'https//www.instegram.com',
            'logo' => 'noon.png',
           'periodtype' => 'year',
            'start_at' => '2022-03-01',
            'end_at' => '2023-03-01',
            'package_id' => 1,
            'country_id' => 1,
            'city_id' =>1,
            'user_id'=>null,
            'special'=>'special',

        ]);
             Store::create([
            'store_name' => 'نون',
            'store_email' => 'j@gmail.com',
            'domain' => 'https//www.n.com',
            'icon' => 'noon.png',
            'phonenumber' => '0096650775433',
            'description' => 'this is noon store',
            'snapchat' => 'https//www.snapchat.com',
            'facebook' => 'https//www.facebook.com',
            'twiter' => 'https//www.twiter.com',
            'youtube' => 'https//www.youtube.com',
            'instegram' => 'https//www.instegram.com',
            'logo' => 'noon.png',
           'periodtype' => 'year',
            'start_at' => '2022-03-01',
            'end_at' => '2023-03-01',
            'package_id' => 1,
            'country_id' => 1,
            'city_id' =>1,
            'user_id'=>null,
            'special'=>'special',

        ]);
          Store::create([
            'store_name' => 'نون',
            'store_email' => 'k@gmail.com',
            'domain' => 'https//www.n.com',
            'icon' => 'noon.png',
            'phonenumber' => '0096650775433',
            'description' => 'this is noon store',
            'snapchat' => 'https//www.snapchat.com',
            'facebook' => 'https//www.facebook.com',
            'twiter' => 'https//www.twiter.com',
            'youtube' => 'https//www.youtube.com',
            'instegram' => 'https//www.instegram.com',
            'logo' => 'noon.png',
           'periodtype' => 'year',
            'start_at' => '2022-03-01',
            'end_at' => '2023-03-01',
            'package_id' => 1,
            'country_id' => 1,
            'city_id' =>1,
            'user_id'=>null,
            'special'=>'special',

        ]);
         Store::create([
            'store_name' => 'نون',
            'store_email' => 'l@gmail.com',
            'domain' => 'https//www.n.com',
            'icon' => 'noon.png',
            'phonenumber' => '0096650775433',
            'description' => 'this is noon store',
            'snapchat' => 'https//www.snapchat.com',
            'facebook' => 'https//www.facebook.com',
            'twiter' => 'https//www.twiter.com',
            'youtube' => 'https//www.youtube.com',
            'instegram' => 'https//www.instegram.com',
            'logo' => 'noon.png',
           'periodtype' => 'year',
            'start_at' => '2022-03-01',
            'end_at' => '2023-03-01',
            'package_id' => 1,
            'country_id' => 1,
            'city_id' =>1,
            'user_id'=>null,
            'special'=>'special',

        ]);
         Store::create([
            'store_name' => 'نون',
            'store_email' => 'm@gmail.com',
            'domain' => 'https//www.n.com',
            'icon' => 'noon.png',
            'phonenumber' => '0096650775433',
            'description' => 'this is noon store',
            'snapchat' => 'https//www.snapchat.com',
            'facebook' => 'https//www.facebook.com',
            'twiter' => 'https//www.twiter.com',
            'youtube' => 'https//www.youtube.com',
            'instegram' => 'https//www.instegram.com',
            'logo' => 'noon.png',
           'periodtype' => 'year',
            'start_at' => '2022-03-01',
            'end_at' => '2023-03-01',
            'package_id' => 1,
            'country_id' => 1,
            'city_id' =>1,
            'user_id'=>null,
            'special'=>'special',

        ]);
        
        Package_store::create([
          'package_id'=>1,
          'store_id'=>1,
          'periodtype' => 'year',
            'start_at' => '2022-03-01',
            'end_at' => '2023-03-01',
        ]);
        Package_store::create([
          'package_id'=>2,
          'store_id'=>2,
          'periodtype' => 'year',
            'start_at' => '2022-03-01',
            'end_at' => '2023-03-01',
        ]);
        Package_store::create([
          'package_id'=>3,
          'store_id'=>2,
          'periodtype' => 'year',
            'start_at' => '2022-03-01',
            'end_at' => '2023-03-01',
        ]);
        activities_stores::create([
       'activity_id'=>1,
         'store_id'=>1
         ]);
         Store::create([
            'store_name' => 'نون',
            'store_email' => 'n@gmail.com',
            'domain' => 'https//www.n.com',
            'icon' => 'noon.png',
            'phonenumber' => '0096650775433',
            'description' => 'this is noon store',
            'snapchat' => 'https//www.snapchat.com',
            'facebook' => 'https//www.facebook.com',
            'twiter' => 'https//www.twiter.com',
            'youtube' => 'https//www.youtube.com',
            'instegram' => 'https//www.instegram.com',
            'logo' => 'noon.png',
           'periodtype' => 'year',
            'start_at' => '2022-03-01',
            'end_at' => '2023-03-01',
            'package_id' => 1,
            'country_id' => 1,
            'city_id' =>1,
            'user_id'=>null,
            'special'=>'special',

        ]);
        
            Store::create([
            'store_name' => 'نون',
            'store_email' => 'b2@gmail.com',
            'domain' => 'https//www.n.com',
            'icon' => 'noon.png',
            'phonenumber' => '0096650775433',
            'description' => 'this is noon store',
            'snapchat' => 'https//www.snapchat.com',
            'facebook' => 'https//www.facebook.com',
            'twiter' => 'https//www.twiter.com',
            'youtube' => 'https//www.youtube.com',
            'instegram' => 'https//www.instegram.com',
            'logo' => 'noon.png',
           'periodtype' => 'year',
            'start_at' => '2022-03-01',
            'end_at' => '2023-03-01',
            'package_id' => 1,
            'country_id' => 1,
            'city_id' =>1,
            'user_id'=>null,
            'special'=>'special',

        ]);
            Store::create([
            'store_name' => 'نون',
            'store_email' => 'b23@gmail.com',
            'domain' => 'https//www.n.com',
            'icon' => 'noon.png',
            'phonenumber' => '0096650775433',
            'description' => 'this is noon store',
            'snapchat' => 'https//www.snapchat.com',
            'facebook' => 'https//www.facebook.com',
            'twiter' => 'https//www.twiter.com',
            'youtube' => 'https//www.youtube.com',
            'instegram' => 'https//www.instegram.com',
            'logo' => 'noon.png',
           'periodtype' => 'year',
            'start_at' => '2022-03-01',
            'end_at' => '2023-03-01',
            'package_id' => 1,
            'country_id' => 1,
            'city_id' =>1,
            'user_id'=>null,
            'special'=>'special',

        ]);
            Store::create([
            'store_name' => 'نون',
            'store_email' => 'b3@gmail.com',
            'domain' => 'https//www.n.com',
            'icon' => 'noon.png',
            'phonenumber' => '0096650775433',
            'description' => 'this is noon store',
            'snapchat' => 'https//www.snapchat.com',
            'facebook' => 'https//www.facebook.com',
            'twiter' => 'https//www.twiter.com',
            'youtube' => 'https//www.youtube.com',
            'instegram' => 'https//www.instegram.com',
            'logo' => 'noon.png',
           'periodtype' => 'year',
            'start_at' => '2022-03-01',
            'end_at' => '2023-03-01',
            'package_id' => 1,
            'country_id' => 1,
            'city_id' =>1,
            'user_id'=>null,
            'special'=>'special',

        ]);
            Store::create([
            'store_name' => 'نون',
            'store_email' => 'b4@gmail.com',
            'domain' => 'https//www.n.com',
            'icon' => 'noon.png',
            'phonenumber' => '0096650775433',
            'description' => 'this is noon store',
            'snapchat' => 'https//www.snapchat.com',
            'facebook' => 'https//www.facebook.com',
            'twiter' => 'https//www.twiter.com',
            'youtube' => 'https//www.youtube.com',
            'instegram' => 'https//www.instegram.com',
            'logo' => 'noon.png',
           'periodtype' => 'year',
            'start_at' => '2022-03-01',
            'end_at' => '2023-03-01',
            'package_id' => 1,
            'country_id' => 1,
            'city_id' =>1,
            'user_id'=>null,
            'special'=>'special',

        ]);
            Store::create([
            'store_name' => 'نون',
            'store_email' => 'b5@gmail.com',
            'domain' => 'https//www.n.com',
            'icon' => 'noon.png',
            'phonenumber' => '0096650775433',
            'description' => 'this is noon store',
            'snapchat' => 'https//www.snapchat.com',
            'facebook' => 'https//www.facebook.com',
            'twiter' => 'https//www.twiter.com',
            'youtube' => 'https//www.youtube.com',
            'instegram' => 'https//www.instegram.com',
            'logo' => 'noon.png',
           'periodtype' => 'year',
            'start_at' => '2022-03-01',
            'end_at' => '2023-03-01',
            'package_id' => 1,
            'country_id' => 1,
            'city_id' =>1,
            'user_id'=>null,
            'special'=>'special',

        ]);
            Store::create([
            'store_name' => 'نون',
            'store_email' => 'b6@gmail.com',
            'domain' => 'https//www.n.com',
            'icon' => 'noon.png',
            'phonenumber' => '0096650775433',
            'description' => 'this is noon store',
            'snapchat' => 'https//www.snapchat.com',
            'facebook' => 'https//www.facebook.com',
            'twiter' => 'https//www.twiter.com',
            'youtube' => 'https//www.youtube.com',
            'instegram' => 'https//www.instegram.com',
            'logo' => 'noon.png',
           'periodtype' => 'year',
            'start_at' => '2022-03-01',
            'end_at' => '2023-03-01',
            'package_id' => 1,
            'country_id' => 1,
            'city_id' =>1,
            'user_id'=>null,
            'special'=>'special',

        ]);
            Store::create([
            'store_name' => 'نون',
            'store_email' => 'b7@gmail.com',
            'domain' => 'https//www.n.com',
            'icon' => 'noon.png',
            'phonenumber' => '0096650775433',
            'description' => 'this is noon store',
            'snapchat' => 'https//www.snapchat.com',
            'facebook' => 'https//www.facebook.com',
            'twiter' => 'https//www.twiter.com',
            'youtube' => 'https//www.youtube.com',
            'instegram' => 'https//www.instegram.com',
            'logo' => 'noon.png',
           'periodtype' => 'year',
            'start_at' => '2022-03-01',
            'end_at' => '2023-03-01',
            'package_id' => 1,
            'country_id' => 1,
            'city_id' =>1,
            'user_id'=>null,
            'special'=>'special',

        ]);
            Store::create([
            'store_name' => 'نون',
            'store_email' => 'b8@gmail.com',
            'domain' => 'https//www.n.com',
            'icon' => 'noon.png',
            'phonenumber' => '0096650775433',
            'description' => 'this is noon store',
            'snapchat' => 'https//www.snapchat.com',
            'facebook' => 'https//www.facebook.com',
            'twiter' => 'https//www.twiter.com',
            'youtube' => 'https//www.youtube.com',
            'instegram' => 'https//www.instegram.com',
            'logo' => 'noon.png',
           'periodtype' => 'year',
            'start_at' => '2022-03-01',
            'end_at' => '2023-03-01',
            'package_id' => 1,
            'country_id' => 1,
            'city_id' =>1,
            'user_id'=>null,
            'special'=>'special',

        ]);
            Store::create([
            'store_name' => 'نون',
            'store_email' => 'b9@gmail.com',
            'domain' => 'https//www.n.com',
            'icon' => 'noon.png',
            'phonenumber' => '0096650775433',
            'description' => 'this is noon store',
            'snapchat' => 'https//www.snapchat.com',
            'facebook' => 'https//www.facebook.com',
            'twiter' => 'https//www.twiter.com',
            'youtube' => 'https//www.youtube.com',
            'instegram' => 'https//www.instegram.com',
            'logo' => 'noon.png',
           'periodtype' => 'year',
            'start_at' => '2022-03-01',
            'end_at' => '2023-03-01',
            'package_id' => 1,
            'country_id' => 1,
            'city_id' =>1,
            'user_id'=>null,
            'special'=>'special',

        ]);
            Store::create([
            'store_name' => 'نون',
            'store_email' => 'b10@gmail.com',
            'domain' => 'https//www.n.com',
            'icon' => 'noon.png',
            'phonenumber' => '0096650775433',
            'description' => 'this is noon store',
            'snapchat' => 'https//www.snapchat.com',
            'facebook' => 'https//www.facebook.com',
            'twiter' => 'https//www.twiter.com',
            'youtube' => 'https//www.youtube.com',
            'instegram' => 'https//www.instegram.com',
            'logo' => 'noon.png',
           'periodtype' => 'year',
            'start_at' => '2022-03-01',
            'end_at' => '2023-03-01',
            'package_id' => 1,
            'country_id' => 1,
            'city_id' =>1,
            'user_id'=>null,
            'special'=>'special',

        ]);
            Store::create([
            'store_name' => 'نون',
            'store_email' => 'b11@gmail.com',
            'domain' => 'https//www.n.com',
            'icon' => 'noon.png',
            'phonenumber' => '0096650775433',
            'description' => 'this is noon store',
            'snapchat' => 'https//www.snapchat.com',
            'facebook' => 'https//www.facebook.com',
            'twiter' => 'https//www.twiter.com',
            'youtube' => 'https//www.youtube.com',
            'instegram' => 'https//www.instegram.com',
            'logo' => 'noon.png',
           'periodtype' => 'year',
            'start_at' => '2022-03-01',
            'end_at' => '2023-03-01',
            'package_id' => 1,
            'country_id' => 1,
            'city_id' =>1,
            'user_id'=>null,
            'special'=>'special',

        ]);
            Store::create([
            'store_name' => 'نون',
            'store_email' => 'b12@gmail.com',
            'domain' => 'https//www.n.com',
            'icon' => 'noon.png',
            'phonenumber' => '0096650775433',
            'description' => 'this is noon store',
            'snapchat' => 'https//www.snapchat.com',
            'facebook' => 'https//www.facebook.com',
            'twiter' => 'https//www.twiter.com',
            'youtube' => 'https//www.youtube.com',
            'instegram' => 'https//www.instegram.com',
            'logo' => 'noon.png',
           'periodtype' => 'year',
            'start_at' => '2022-03-01',
            'end_at' => '2023-03-01',
            'package_id' => 1,
            'country_id' => 1,
            'city_id' =>1,
            'user_id'=>null,
            'special'=>'special',

        ]);
            Store::create([
            'store_name' => 'نون',
            'store_email' => 'b13@gmail.com',
            'domain' => 'https//www.n.com',
            'icon' => 'noon.png',
            'phonenumber' => '0096650775433',
            'description' => 'this is noon store',
            'snapchat' => 'https//www.snapchat.com',
            'facebook' => 'https//www.facebook.com',
            'twiter' => 'https//www.twiter.com',
            'youtube' => 'https//www.youtube.com',
            'instegram' => 'https//www.instegram.com',
            'logo' => 'noon.png',
           'periodtype' => 'year',
            'start_at' => '2022-03-01',
            'end_at' => '2023-03-01',
            'package_id' => 1,
            'country_id' => 1,
            'city_id' =>1,
            'user_id'=>null,
            'special'=>'special',

        ]);
            Store::create([
            'store_name' => 'نون',
            'store_email' => 'b14@gmail.com',
            'domain' => 'https//www.n.com',
            'icon' => 'noon.png',
            'phonenumber' => '0096650775433',
            'description' => 'this is noon store',
            'snapchat' => 'https//www.snapchat.com',
            'facebook' => 'https//www.facebook.com',
            'twiter' => 'https//www.twiter.com',
            'youtube' => 'https//www.youtube.com',
            'instegram' => 'https//www.instegram.com',
            'logo' => 'noon.png',
           'periodtype' => 'year',
            'start_at' => '2022-03-01',
            'end_at' => '2023-03-01',
            'package_id' => 1,
            'country_id' => 1,
            'city_id' =>1,
            'user_id'=>null,
            'special'=>'special',

        ]);
            Store::create([
            'store_name' => 'نون',
            'store_email' => 'b15@gmail.com',
            'domain' => 'https//www.n.com',
            'icon' => 'noon.png',
            'phonenumber' => '0096650775433',
            'description' => 'this is noon store',
            'snapchat' => 'https//www.snapchat.com',
            'facebook' => 'https//www.facebook.com',
            'twiter' => 'https//www.twiter.com',
            'youtube' => 'https//www.youtube.com',
            'instegram' => 'https//www.instegram.com',
            'logo' => 'noon.png',
           'periodtype' => 'year',
            'start_at' => '2022-03-01',
            'end_at' => '2023-03-01',
            'package_id' => 1,
            'country_id' => 1,
            'city_id' =>1,
            'user_id'=>null,
            'special'=>'special',

        ]);
            Store::create([
            'store_name' => 'نون',
            'store_email' => 'b16@gmail.com',
            'domain' => 'https//www.n.com',
            'icon' => 'noon.png',
            'phonenumber' => '0096650775433',
            'description' => 'this is noon store',
            'snapchat' => 'https//www.snapchat.com',
            'facebook' => 'https//www.facebook.com',
            'twiter' => 'https//www.twiter.com',
            'youtube' => 'https//www.youtube.com',
            'instegram' => 'https//www.instegram.com',
            'logo' => 'noon.png',
           'periodtype' => 'year',
            'start_at' => '2022-03-01',
            'end_at' => '2023-03-01',
            'package_id' => 1,
            'country_id' => 1,
            'city_id' =>1,
            'user_id'=>null,
            'special'=>'special',

        ]);
            Store::create([
            'store_name' => 'نون',
            'store_email' => 'b17@gmail.com',
            'domain' => 'https//www.n.com',
            'icon' => 'noon.png',
            'phonenumber' => '0096650775433',
            'description' => 'this is noon store',
            'snapchat' => 'https//www.snapchat.com',
            'facebook' => 'https//www.facebook.com',
            'twiter' => 'https//www.twiter.com',
            'youtube' => 'https//www.youtube.com',
            'instegram' => 'https//www.instegram.com',
            'logo' => 'noon.png',
           'periodtype' => 'year',
            'start_at' => '2022-03-01',
            'end_at' => '2023-03-01',
            'package_id' => 1,
            'country_id' => 1,
            'city_id' =>1,
            'user_id'=>null,
            'special'=>'special',

        ]);
            Store::create([
            'store_name' => 'نون',
            'store_email' => 'b18@gmail.com',
            'domain' => 'https//www.n.com',
            'icon' => 'noon.png',
            'phonenumber' => '0096650775433',
            'description' => 'this is noon store',
            'snapchat' => 'https//www.snapchat.com',
            'facebook' => 'https//www.facebook.com',
            'twiter' => 'https//www.twiter.com',
            'youtube' => 'https//www.youtube.com',
            'instegram' => 'https//www.instegram.com',
            'logo' => 'noon.png',
           'periodtype' => 'year',
            'start_at' => '2022-03-01',
            'end_at' => '2023-03-01',
            'package_id' => 1,
            'country_id' => 1,
            'city_id' =>1,
            'user_id'=>null,
            'special'=>'special',

        ]);
            Store::create([
            'store_name' => 'نون',
            'store_email' => 'b19@gmail.com',
            'domain' => 'https//www.n.com',
            'icon' => 'noon.png',
            'phonenumber' => '0096650775433',
            'description' => 'this is noon store',
            'snapchat' => 'https//www.snapchat.com',
            'facebook' => 'https//www.facebook.com',
            'twiter' => 'https//www.twiter.com',
            'youtube' => 'https//www.youtube.com',
            'instegram' => 'https//www.instegram.com',
            'logo' => 'noon.png',
           'periodtype' => 'year',
            'start_at' => '2022-03-01',
            'end_at' => '2023-03-01',
            'package_id' => 1,
            'country_id' => 1,
            'city_id' =>1,
            'user_id'=>null,
            'special'=>'special',

        ]);
            Store::create([
            'store_name' => 'نون',
            'store_email' => 'b20@gmail.com',
            'domain' => 'https//www.n.com',
            'icon' => 'noon.png',
            'phonenumber' => '0096650775433',
            'description' => 'this is noon store',
            'snapchat' => 'https//www.snapchat.com',
            'facebook' => 'https//www.facebook.com',
            'twiter' => 'https//www.twiter.com',
            'youtube' => 'https//www.youtube.com',
            'instegram' => 'https//www.instegram.com',
            'logo' => 'noon.png',
           'periodtype' => 'year',
            'start_at' => '2022-03-01',
            'end_at' => '2023-03-01',
            'package_id' => 1,
            'country_id' => 1,
            'city_id' =>1,
            'user_id'=>null,
            'special'=>'special',

        ]);
            Store::create([
            'store_name' => 'نون',
            'store_email' => 'b21@gmail.com',
            'domain' => 'https//www.n.com',
            'icon' => 'noon.png',
            'phonenumber' => '0096650775433',
            'description' => 'this is noon store',
            'snapchat' => 'https//www.snapchat.com',
            'facebook' => 'https//www.facebook.com',
            'twiter' => 'https//www.twiter.com',
            'youtube' => 'https//www.youtube.com',
            'instegram' => 'https//www.instegram.com',
            'logo' => 'noon.png',
           'periodtype' => 'year',
            'start_at' => '2022-03-01',
            'end_at' => '2023-03-01',
            'package_id' => 1,
            'country_id' => 1,
            'city_id' =>1,
            'user_id'=>null,
            'special'=>'special',

        ]);
            Store::create([
            'store_name' => 'نون',
            'store_email' => 'b22@gmail.com',
            'domain' => 'https//www.n.com',
            'icon' => 'noon.png',
            'phonenumber' => '0096650775433',
            'description' => 'this is noon store',
            'snapchat' => 'https//www.snapchat.com',
            'facebook' => 'https//www.facebook.com',
            'twiter' => 'https//www.twiter.com',
            'youtube' => 'https//www.youtube.com',
            'instegram' => 'https//www.instegram.com',
            'logo' => 'noon.png',
           'periodtype' => 'year',
            'start_at' => '2022-03-01',
            'end_at' => '2023-03-01',
            'package_id' => 1,
            'country_id' => 1,
            'city_id' =>1,
            'user_id'=>null,
            'special'=>'special',

        ]);
         Store::create([
            'store_name' => 'امازون',
            'store_email' => 'o@gmail.com',
            'domain' => 'https//www.a.com',
            'icon' => 'Amazon_logo.png',
            'phonenumber' => '0096650775433',
            'description' => 'this is amazon store',
            'snapchat' => 'https//www.snapchat.com',
            'facebook' => 'https//www.facebook.com',
            'twiter' => 'https//www.twiter.com',
            'youtube' => 'https//www.youtube.com',
            'instegram' => 'https//www.instegram.com',
            'logo' => 'Amazon_logo.png',
            'periodtype' => 'year',
            'start_at' => '2022-03-01',
            'end_at' => '2023-03-01',
            'package_id' => 1,
            'country_id' => 1,
            'city_id' =>1,
             'user_id'=>null,
             'special'=>'special',

        ]);


    //      Store::create([
    //         'store_name' => 'نون',
    //         'store_email' => '@gmail.com',
    //         'domain' => 'https//www.n.com',
    //         'icon' => 'noon.png',
    //         'phonenumber' => '0096650775433',
    //         'description' => 'this is noon store',
    //         'snapchat' => 'https//www.snapchat.com',
    //         'facebook' => 'https//www.facebook.com',
    //         'twiter' => 'https//www.twiter.com',
    //         'youtube' => 'https//www.youtube.com',
    //         'instegram' => 'https//www.instegram.com',
    //         'logo' => 'noon.png',
    //        'periodtype' => 'year',
    //         'start_at' => '2022-03-01',
    //         'end_at' => '2023-03-01',
    //         'package_id' => 1,
    //         'country_id' => 1,
    //         'city_id' =>1,
    //         'user_id'=>null,
    //         'special'=>'special',

    //     ]);
    //          Store::create([
    //         'store_name' => 'نون',
    //         'store_email' => 'n@gmail.com',
    //         'domain' => 'https//www.n.com',
    //         'icon' => 'noon.png',
    //         'phonenumber' => '0096650775433',
    //         'description' => 'this is noon store',
    //         'snapchat' => 'https//www.snapchat.com',
    //         'facebook' => 'https//www.facebook.com',
    //         'twiter' => 'https//www.twiter.com',
    //         'youtube' => 'https//www.youtube.com',
    //         'instegram' => 'https//www.instegram.com',
    //         'logo' => 'noon.png',
    //        'periodtype' => 'year',
    //         'start_at' => '2022-03-01',
    //         'end_at' => '2023-03-01',
    //         'package_id' => 1,
    //         'country_id' => 1,
    //         'city_id' =>1,
    //         'user_id'=>null,
    //         'special'=>'special',

    //     ]);
    //       Store::create([
    //         'store_name' => 'نون',
    //         'store_email' => 'n@gmail.com',
    //         'domain' => 'https//www.n.com',
    //         'icon' => 'noon.png',
    //         'phonenumber' => '0096650775433',
    //         'description' => 'this is noon store',
    //         'snapchat' => 'https//www.snapchat.com',
    //         'facebook' => 'https//www.facebook.com',
    //         'twiter' => 'https//www.twiter.com',
    //         'youtube' => 'https//www.youtube.com',
    //         'instegram' => 'https//www.instegram.com',
    //         'logo' => 'noon.png',
    //        'periodtype' => 'year',
    //         'start_at' => '2022-03-01',
    //         'end_at' => '2023-03-01',
    //         'package_id' => 1,
    //         'country_id' => 1,
    //         'city_id' =>1,
    //         'user_id'=>null,
    //         'special'=>'special',

    //     ]);
    //      Store::create([
    //         'store_name' => 'نون',
    //         'store_email' => 'n@gmail.com',
    //         'domain' => 'https//www.n.com',
    //         'icon' => 'noon.png',
    //         'phonenumber' => '0096650775433',
    //         'description' => 'this is noon store',
    //         'snapchat' => 'https//www.snapchat.com',
    //         'facebook' => 'https//www.facebook.com',
    //         'twiter' => 'https//www.twiter.com',
    //         'youtube' => 'https//www.youtube.com',
    //         'instegram' => 'https//www.instegram.com',
    //         'logo' => 'noon.png',
    //        'periodtype' => 'year',
    //         'start_at' => '2022-03-01',
    //         'end_at' => '2023-03-01',
    //         'package_id' => 1,
    //         'country_id' => 1,
    //         'city_id' =>1,
    //         'user_id'=>null,
    //         'special'=>'special',

    //     ]);
    //      Store::create([
    //         'store_name' => 'نون',
    //         'store_email' => 'n@gmail.com',
    //         'domain' => 'https//www.n.com',
    //         'icon' => 'noon.png',
    //         'phonenumber' => '0096650775433',
    //         'description' => 'this is noon store',
    //         'snapchat' => 'https//www.snapchat.com',
    //         'facebook' => 'https//www.facebook.com',
    //         'twiter' => 'https//www.twiter.com',
    //         'youtube' => 'https//www.youtube.com',
    //         'instegram' => 'https//www.instegram.com',
    //         'logo' => 'noon.png',
    //        'periodtype' => 'year',
    //         'start_at' => '2022-03-01',
    //         'end_at' => '2023-03-01',
    //         'package_id' => 1,
    //         'country_id' => 1,
    //         'city_id' =>1,
    //         'user_id'=>null,
    //         'special'=>'special',

    //     ]);
    //      Store::create([
    //         'store_name' => 'نون',
    //         'store_email' => 'n@gmail.com',
    //         'domain' => 'https//www.n.com',
    //         'icon' => 'noon.png',
    //         'phonenumber' => '0096650775433',
    //         'description' => 'this is noon store',
    //         'snapchat' => 'https//www.snapchat.com',
    //         'facebook' => 'https//www.facebook.com',
    //         'twiter' => 'https//www.twiter.com',
    //         'youtube' => 'https//www.youtube.com',
    //         'instegram' => 'https//www.instegram.com',
    //         'logo' => 'noon.png',
    //        'periodtype' => 'year',
    //         'start_at' => '2022-03-01',
    //         'end_at' => '2023-03-01',
    //         'package_id' => 1,
    //         'country_id' => 1,
    //         'city_id' =>1,
    //         'user_id'=>null,
    //         'special'=>'special',

    //     ]);
    //      Store::create([
    //         'store_name' => 'امازون',
    //         'store_email' => 'a@gmail.com',
    //         'domain' => 'https//www.a.com',
    //         'icon' => 'Amazon_logo.png',
    //         'phonenumber' => '0096650775433',
    //         'description' => 'this is amazon store',
    //         'snapchat' => 'https//www.snapchat.com',
    //         'facebook' => 'https//www.facebook.com',
    //         'twiter' => 'https//www.twiter.com',
    //         'youtube' => 'https//www.youtube.com',
    //         'instegram' => 'https//www.instegram.com',
    //         'logo' => 'Amazon_logo.png',
    //         'periodtype' => 'year',
    //         'start_at' => '2022-03-01',
    //         'end_at' => '2023-03-01',
    //         'package_id' => 1,
    //         'country_id' => 1,
    //         'city_id' =>1,
    //          'user_id'=>null,
    //          'special'=>'special',

    //     ]);


    //      Store::create([
    //         'store_name' => 'نون',
    //         'store_email' => 'n@gmail.com',
    //         'domain' => 'https//www.n.com',
    //         'icon' => 'noon.png',
    //         'phonenumber' => '0096650775433',
    //         'description' => 'this is noon store',
    //         'snapchat' => 'https//www.snapchat.com',
    //         'facebook' => 'https//www.facebook.com',
    //         'twiter' => 'https//www.twiter.com',
    //         'youtube' => 'https//www.youtube.com',
    //         'instegram' => 'https//www.instegram.com',
    //         'logo' => 'noon.png',
    //        'periodtype' => 'year',
    //         'start_at' => '2022-03-01',
    //         'end_at' => '2023-03-01',
    //         'package_id' => 1,
    //         'country_id' => 1,
    //         'city_id' =>1,
    //         'user_id'=>null,
    //         'special'=>'special',

    //     ]);
    //          Store::create([
    //         'store_name' => 'نون',
    //         'store_email' => 'n@gmail.com',
    //         'domain' => 'https//www.n.com',
    //         'icon' => 'noon.png',
    //         'phonenumber' => '0096650775433',
    //         'description' => 'this is noon store',
    //         'snapchat' => 'https//www.snapchat.com',
    //         'facebook' => 'https//www.facebook.com',
    //         'twiter' => 'https//www.twiter.com',
    //         'youtube' => 'https//www.youtube.com',
    //         'instegram' => 'https//www.instegram.com',
    //         'logo' => 'noon.png',
    //        'periodtype' => 'year',
    //         'start_at' => '2022-03-01',
    //         'end_at' => '2023-03-01',
    //         'package_id' => 1,
    //         'country_id' => 1,
    //         'city_id' =>1,
    //         'user_id'=>null,
    //         'special'=>'special',

    //     ]);
    //       Store::create([
    //         'store_name' => 'نون',
    //         'store_email' => 'n@gmail.com',
    //         'domain' => 'https//www.n.com',
    //         'icon' => 'noon.png',
    //         'phonenumber' => '0096650775433',
    //         'description' => 'this is noon store',
    //         'snapchat' => 'https//www.snapchat.com',
    //         'facebook' => 'https//www.facebook.com',
    //         'twiter' => 'https//www.twiter.com',
    //         'youtube' => 'https//www.youtube.com',
    //         'instegram' => 'https//www.instegram.com',
    //         'logo' => 'noon.png',
    //        'periodtype' => 'year',
    //         'start_at' => '2022-03-01',
    //         'end_at' => '2023-03-01',
    //         'package_id' => 1,
    //         'country_id' => 1,
    //         'city_id' =>1,
    //         'user_id'=>null,
    //         'special'=>'special',

    //     ]);
    //      Store::create([
    //         'store_name' => 'نون',
    //         'store_email' => 'n@gmail.com',
    //         'domain' => 'https//www.n.com',
    //         'icon' => 'noon.png',
    //         'phonenumber' => '0096650775433',
    //         'description' => 'this is noon store',
    //         'snapchat' => 'https//www.snapchat.com',
    //         'facebook' => 'https//www.facebook.com',
    //         'twiter' => 'https//www.twiter.com',
    //         'youtube' => 'https//www.youtube.com',
    //         'instegram' => 'https//www.instegram.com',
    //         'logo' => 'noon.png',
    //        'periodtype' => 'year',
    //         'start_at' => '2022-03-01',
    //         'end_at' => '2023-03-01',
    //         'package_id' => 1,
    //         'country_id' => 1,
    //         'city_id' =>1,
    //         'user_id'=>null,
    //         'special'=>'special',

    //     ]);
    //      Store::create([
    //         'store_name' => 'نون',
    //         'store_email' => 'n@gmail.com',
    //         'domain' => 'https//www.n.com',
    //         'icon' => 'noon.png',
    //         'phonenumber' => '0096650775433',
    //         'description' => 'this is noon store',
    //         'snapchat' => 'https//www.snapchat.com',
    //         'facebook' => 'https//www.facebook.com',
    //         'twiter' => 'https//www.twiter.com',
    //         'youtube' => 'https//www.youtube.com',
    //         'instegram' => 'https//www.instegram.com',
    //         'logo' => 'noon.png',
    //        'periodtype' => 'year',
    //         'start_at' => '2022-03-01',
    //         'end_at' => '2023-03-01',
    //         'package_id' => 1,
    //         'country_id' => 1,
    //         'city_id' =>1,
    //         'user_id'=>null,
    //         'special'=>'special',

    //     ]);
    //      Store::create([
    //         'store_name' => 'نون',
    //         'store_email' => 'n@gmail.com',
    //         'domain' => 'https//www.n.com',
    //         'icon' => 'noon.png',
    //         'phonenumber' => '0096650775433',
    //         'description' => 'this is noon store',
    //         'snapchat' => 'https//www.snapchat.com',
    //         'facebook' => 'https//www.facebook.com',
    //         'twiter' => 'https//www.twiter.com',
    //         'youtube' => 'https//www.youtube.com',
    //         'instegram' => 'https//www.instegram.com',
    //         'logo' => 'noon.png',
    //        'periodtype' => 'year',
    //         'start_at' => '2022-03-01',
    //         'end_at' => '2023-03-01',
    //         'package_id' => 1,
    //         'country_id' => 1,
    //         'city_id' =>1,
    //         'user_id'=>null,
    //         'special'=>'special',

    //     ]);
    //      Store::create([
    //         'store_name' => 'امازون',
    //         'store_email' => 'a@gmail.com',
    //         'domain' => 'https//www.a.com',
    //         'icon' => 'Amazon_logo.png',
    //         'phonenumber' => '0096650775433',
    //         'description' => 'this is amazon store',
    //         'snapchat' => 'https//www.snapchat.com',
    //         'facebook' => 'https//www.facebook.com',
    //         'twiter' => 'https//www.twiter.com',
    //         'youtube' => 'https//www.youtube.com',
    //         'instegram' => 'https//www.instegram.com',
    //         'logo' => 'Amazon_logo.png',
    //         'periodtype' => 'year',
    //         'start_at' => '2022-03-01',
    //         'end_at' => '2023-03-01',
    //         'package_id' => 1,
    //         'country_id' => 1,
    //         'city_id' =>1,
    //          'user_id'=>null,
    //          'special'=>'special',

    //     ]);


    //      Store::create([
    //         'store_name' => 'نون',
    //         'store_email' => 'n@gmail.com',
    //         'domain' => 'https//www.n.com',
    //         'icon' => 'noon.png',
    //         'phonenumber' => '0096650775433',
    //         'description' => 'this is noon store',
    //         'snapchat' => 'https//www.snapchat.com',
    //         'facebook' => 'https//www.facebook.com',
    //         'twiter' => 'https//www.twiter.com',
    //         'youtube' => 'https//www.youtube.com',
    //         'instegram' => 'https//www.instegram.com',
    //         'logo' => 'noon.png',
    //        'periodtype' => 'year',
    //         'start_at' => '2022-03-01',
    //         'end_at' => '2023-03-01',
    //         'package_id' => 1,
    //         'country_id' => 1,
    //         'city_id' =>1,
    //         'user_id'=>null,
    //         'special'=>'special',

    //     ]);
    //          Store::create([
    //         'store_name' => 'نون',
    //         'store_email' => 'n@gmail.com',
    //         'domain' => 'https//www.n.com',
    //         'icon' => 'noon.png',
    //         'phonenumber' => '0096650775433',
    //         'description' => 'this is noon store',
    //         'snapchat' => 'https//www.snapchat.com',
    //         'facebook' => 'https//www.facebook.com',
    //         'twiter' => 'https//www.twiter.com',
    //         'youtube' => 'https//www.youtube.com',
    //         'instegram' => 'https//www.instegram.com',
    //         'logo' => 'noon.png',
    //        'periodtype' => 'year',
    //         'start_at' => '2022-03-01',
    //         'end_at' => '2023-03-01',
    //         'package_id' => 1,
    //         'country_id' => 1,
    //         'city_id' =>1,
    //         'user_id'=>null,
    //         'special'=>'special',

    //     ]);
    //       Store::create([
    //         'store_name' => 'نون',
    //         'store_email' => 'n@gmail.com',
    //         'domain' => 'https//www.n.com',
    //         'icon' => 'noon.png',
    //         'phonenumber' => '0096650775433',
    //         'description' => 'this is noon store',
    //         'snapchat' => 'https//www.snapchat.com',
    //         'facebook' => 'https//www.facebook.com',
    //         'twiter' => 'https//www.twiter.com',
    //         'youtube' => 'https//www.youtube.com',
    //         'instegram' => 'https//www.instegram.com',
    //         'logo' => 'noon.png',
    //        'periodtype' => 'year',
    //         'start_at' => '2022-03-01',
    //         'end_at' => '2023-03-01',
    //         'package_id' => 1,
    //         'country_id' => 1,
    //         'city_id' =>1,
    //         'user_id'=>null,
    //         'special'=>'special',

    //     ]);
    //      Store::create([
    //         'store_name' => 'نون',
    //         'store_email' => 'n@gmail.com',
    //         'domain' => 'https//www.n.com',
    //         'icon' => 'noon.png',
    //         'phonenumber' => '0096650775433',
    //         'description' => 'this is noon store',
    //         'snapchat' => 'https//www.snapchat.com',
    //         'facebook' => 'https//www.facebook.com',
    //         'twiter' => 'https//www.twiter.com',
    //         'youtube' => 'https//www.youtube.com',
    //         'instegram' => 'https//www.instegram.com',
    //         'logo' => 'noon.png',
    //        'periodtype' => 'year',
    //         'start_at' => '2022-03-01',
    //         'end_at' => '2023-03-01',
    //         'package_id' => 1,
    //         'country_id' => 1,
    //         'city_id' =>1,
    //         'user_id'=>null,
    //         'special'=>'special',

    //     ]);
    //      Store::create([
    //         'store_name' => 'نون',
    //         'store_email' => 'n@gmail.com',
    //         'domain' => 'https//www.n.com',
    //         'icon' => 'noon.png',
    //         'phonenumber' => '0096650775433',
    //         'description' => 'this is noon store',
    //         'snapchat' => 'https//www.snapchat.com',
    //         'facebook' => 'https//www.facebook.com',
    //         'twiter' => 'https//www.twiter.com',
    //         'youtube' => 'https//www.youtube.com',
    //         'instegram' => 'https//www.instegram.com',
    //         'logo' => 'noon.png',
    //        'periodtype' => 'year',
    //         'start_at' => '2022-03-01',
    //         'end_at' => '2023-03-01',
    //         'package_id' => 1,
    //         'country_id' => 1,
    //         'city_id' =>1,
    //         'user_id'=>null,
    //         'special'=>'special',

    //     ]);
    //      Store::create([
    //         'store_name' => 'نون',
    //         'store_email' => 'n@gmail.com',
    //         'domain' => 'https//www.n.com',
    //         'icon' => 'noon.png',
    //         'phonenumber' => '0096650775433',
    //         'description' => 'this is noon store',
    //         'snapchat' => 'https//www.snapchat.com',
    //         'facebook' => 'https//www.facebook.com',
    //         'twiter' => 'https//www.twiter.com',
    //         'youtube' => 'https//www.youtube.com',
    //         'instegram' => 'https//www.instegram.com',
    //         'logo' => 'noon.png',
    //        'periodtype' => 'year',
    //         'start_at' => '2022-03-01',
    //         'end_at' => '2023-03-01',
    //         'package_id' => 1,
    //         'country_id' => 1,
    //         'city_id' =>1,
    //         'user_id'=>null,
    //         'special'=>'special',

    //     ]);
    //     activities_stores::create([
    //    'activity_id'=>1,
    //      'store_id'=>1
    //     ]);
    //       activities_stores::create([
    //    'activity_id'=>1,
    //      'store_id'=>2
    //     ]);


    // Package_store::create([
    //       'package_id'=>1,
    //       'store_id'=>1,
    //       'periodtype' => 'year',
    //         'start_at' => '2022-03-01',
    //         'end_at' => '2023-03-01',
    //     ]);
    //     Package_store::create([
    //       'package_id'=>2,
    //       'store_id'=>2,
    //       'periodtype' => 'year',
    //         'start_at' => '2022-03-01',
    //         'end_at' => '2023-03-01',
    //     ]);
    //     Package_store::create([
    //       'package_id'=>3,
    //       'store_id'=>3,
    //       'periodtype' => 'year',
    //         'start_at' => '2022-03-01',
    //         'end_at' => '2023-03-01',
    //     ]);
    }
}
